name: Build JackieBlue

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build EasyWinHax
        run: msbuild .\EasyWinHax\EasyWinHax.vcxproj /m /p:Configuration=Release /p:Platform=x64

      - name: Build JackieBlue
        run: msbuild .\JackieBlue.vcxproj /m /p:Configuration=Release /p:Platform=x64

      - name: Find output
        shell: pwsh
        run: Get-ChildItem -Recurse -Filter JackieBlue.exe

      - name: Upload JackieBlue
        uses: actions/upload-artifact@v4
        with:
          name: JackieBlue-x64
          path: |
            **/JackieBlue.exe
